export const BATCH_SIZE = 50;

export const PAGE_TYPES_TO_EXCLUDE = [
  "pdf",
  "doc",
  "docx",
  "xls",
  "xlsx",
  "ppt",
  "pptx",
  "zip",
  "rar",
  "7z",
  "tar",
  "gz",
  "exe",
  "dmg",
  "iso",
  "jpg",
  "jpeg",
  "png",
  "gif",
  "bmp",
  "svg",
  "webp",
  "mp4",
  "mp3",
  "avi",
  "mkv",
  "mov",
  "wmv",
  "flv",
  "txt",
  "rtf",
  "csv",
  "json",
  "xml",
];

export const TRUSTED_WEBSITES_TO_EXCLUDE = [
  // Video & Streaming Platforms
  "youtube.com",
  "vimeo.com",
  "twitch.tv",
  "netflix.com",
  "hulu.com",
  "primevideo.com",
  "disney.com",
  "hbo.com",
  "peacocktv.com",
  "paramount.com",
  "crunchyroll.com",
  "funimation.com",
  "dailymotion.com",

  // Social Media Platforms (Mainstream)
  "facebook.com",
  "instagram.com",
  "twitter.com",
  "x.com",
  "linkedin.com",
  "tiktok.com",
  "snapchat.com",
  "pinterest.com",
  "tumblr.com",
  "reddit.com",
  "discord.com",
  "telegram.org",
  "whatsapp.com",

  // Professional Stock Photo/Media Sites
  "shutterstock.com",
  "gettyimages.com",
  "istockphoto.com",
  "adobe.com",
  "unsplash.com",
  "pexels.com",
  "pixabay.com",
  "freepik.com",
  "depositphotos.com",
  "alamy.com",
  "123rf.com",
  "dreamstime.com",
  "stocksy.com",
  "pond5.com",
  "burst.shopify.com",
  "picjumbo.com",
  "gratisography.com",

  // Developer & Tech Platforms
  "github.com",
  "gitlab.com",
  "bitbucket.org",
  "stackoverflow.com",
  "stackexchange.com",
  "codepen.io",
  "jsfiddle.net",
  "replit.com",
  "glitch.com",
  "codesandbox.io",
  "npmjs.com",
  "pypi.org",
  "crates.io",
  "dockerhub.com",
  "maven.apache.org",

  // Educational Institutions & Platforms
  "coursera.org",
  "edx.org",
  "udemy.com",
  "khanacademy.org",
  "mit.edu",
  "stanford.edu",
  "harvard.edu",
  "berkeley.edu",
  "ox.ac.uk",
  "cam.ac.uk",
  "codecademy.com",
  "freecodecamp.org",
  "udacity.com",
  "pluralsight.com",
  "lynda.com",
  "linkedin.com/learning",

  // E-commerce & Retail
  "amazon.com",
  "ebay.com",
  "walmart.com",
  "target.com",
  "bestbuy.com",
  "costco.com",
  "shopify.com",
  "etsy.com",
  "alibaba.com",
  "aliexpress.com",
  "wish.com",
  "overstock.com",
  "wayfair.com",

  // News & Media Organizations
  "cnn.com",
  "bbc.com",
  "reuters.com",
  "ap.org",
  "nytimes.com",
  "washingtonpost.com",
  "theguardian.com",
  "wsj.com",
  "npr.org",
  "pbs.org",
  "abc.com",
  "nbc.com",
  "cbs.com",
  "fox.com",
  "bloomberg.com",
  "fortune.com",
  "forbes.com",
  "time.com",
  "newsweek.com",
  "usatoday.com",

  // Government & Official Sites
  "gov",
  "edu",
  "mil",
  "whitehouse.gov",
  "nih.gov",
  "cdc.gov",
  "fda.gov",
  "nasa.gov",
  "un.org",
  "who.int",
  "europa.eu",
  "gov.uk",
  "canada.ca",
  "australia.gov.au",

  // Cloud & Enterprise Services
  "google.com",
  "microsoft.com",
  "apple.com",
  "ibm.com",
  "oracle.com",
  "salesforce.com",
  "atlassian.com",
  "slack.com",
  "zoom.us",
  "teams.microsoft.com",
  "dropbox.com",
  "box.com",
  "onedrive.com",
  "icloud.com",
  "notion.so",
  "airtable.com",
  "trello.com",
  "asana.com",
  "monday.com",

  // Search Engines & Maps
  "google.com",
  "bing.com",
  "yahoo.com",
  "duckduckgo.com",
  "yandex.com",
  "baidu.com",
  "maps.google.com",
  "openstreetmap.org",

  // Financial Services
  "paypal.com",
  "stripe.com",
  "square.com",
  "visa.com",
  "mastercard.com",
  "americanexpress.com",
  "bankofamerica.com",
  "chase.com",
  "wellsfargo.com",
  "citibank.com",

  // Travel & Transportation
  "booking.com",
  "expedia.com",
  "airbnb.com",
  "hotels.com",
  "tripadvisor.com",
  "kayak.com",
  "priceline.com",
  "uber.com",
  "lyft.com",
  "delta.com",
  "united.com",
  "american.com",

  // Health & Medical
  "webmd.com",
  "mayoclinic.org",
  "healthline.com",
  "medscape.com",
  "nih.gov",
  "cdc.gov",
  "who.int",
  "pubmed.ncbi.nlm.nih.gov",

  // Gaming Platforms
  "steam.com",
  "epicgames.com",
  "origin.com",
  "uplay.com",
  "gog.com",
  "battle.net",
  "xbox.com",
  "playstation.com",
  "nintendo.com",

  // Music & Audio
  "spotify.com",
  "apple.com/music",
  "youtube.com/music",
  "soundcloud.com",
  "pandora.com",
  "tidal.com",
  "deezer.com",
  "bandcamp.com",
  "audible.com",

  // Productivity & Office
  "office.com",
  "docs.google.com",
  "sheets.google.com",
  "slides.google.com",
  "drive.google.com",
  "canva.com",
  "figma.com",
  "sketch.com",
  "adobe.com/products/photoshop",
  "adobe.com/products/illustrator",

  // Wikis & Reference
  "wikipedia.org",
  "wikimedia.org",
  "wiktionary.org",
  "archive.org",
  "dictionary.com",
  "merriam-webster.com",
  "britannica.com",

  // Food & Recipes
  "allrecipes.com",
  "foodnetwork.com",
  "epicurious.com",
  "tastingtable.com",
  "bonappetit.com",
  "seriouseats.com",
  "delish.com",

  // Weather & Environment
  "weather.com",
  "accuweather.com",
  "weather.gov",
  "wunderground.com",
  "climate.gov",

  // Sports & Entertainment
  "espn.com",
  "nfl.com",
  "nba.com",
  "mlb.com",
  "nhl.com",
  "fifa.com",
  "olympics.com",
  "imdb.com",
  "rottentomatoes.com",
  "metacritic.com",

  // Specialized Professional Sites
  "behance.net",
  "dribbble.com",
  "deviantart.com",
  "artstation.com",
  "flickr.com",
  "500px.com",
  "smugmug.com",
];

export const EXCLUDE_PATTERNS = [
  new RegExp(`\\.(${PAGE_TYPES_TO_EXCLUDE.join("|")})$`, "i"),
  new RegExp(`(${TRUSTED_WEBSITES_TO_EXCLUDE.join("|").replace(/\./g, "\\.")})`, "i"),
  /^javascript:/i,
  /^mailto:/i,
  /^tel:/i,
  /^#/,
  /^void\(0\)/i,
];
